export const data = [
  {
    id: "16500",
    english: "ginger",
    transcription: "[ˈʤɪnʤə]",
    russian: "имбирь",
    tags: "food",
    tags_json: '[""]',
  },
  {
    id: "16502",
    english: "waterfall",
    transcription: "[ˈwɔ:təfɔ:l]",
    russian: "водопад",
    tags: "nature",
    tags_json: '[""]',
  },
  {
    id: "16504",
    english: "story",
    transcription: "[ˈstôrē]",
    russian: "история",
    tags: "basic",
    tags_json: '[""]',
  },
  {
    id: "16506",
    english: "first",
    transcription: "[fərst]",
    russian: "первый",
    tags: "basic",
    tags_json: '[""]',
  },
  {
    id: "16507",
    english: "sucсess",
    transcription: "[sucsess]",
    russian: "успех",
    tags: "basic",
    tags_json: '[""]',
  },
  {
    id: "16508",
    english: "sunset",
    transcription: "[ˈsʌnset]",
    russian: "закат",
    tags: "nature",
    tags_json: '[""]',
  },
  {
    id: "16509",
    english: "wind",
    transcription: "[wind]",
    russian: "ветер",
    tags: "nature",
    tags_json: '[""]',
  },
  {
    id: "16510",
    english: "field",
    transcription: "[fi:ld]",
    russian: "поле",
    tags: "nature",
    tags_json: '[""]',
  },
  {
    id: "16511",
    english: "cat",
    transcription: "[cat]",
    russian: "кот",
    tags: "basic",
    tags_json: '[""]',
  },
  {
    id: "16520",
    english: "ground",
    transcription: "[gra:und]",
    russian: "земля",
    tags: "nature",
    tags_json: "[]",
  },
  {
    id: "16524",
    english: "book",
    transcription: "[buk]",
    russian: "книжка",
    tags: "basic",
    tags_json: '[""]',
  },
  {
    id: "16525",
    english: "thunderstorm",
    transcription: " [ˈθʌndəstɔ:m]",
    russian: "гроза",
    tags: "nature",
    tags_json: '[""]',
  },
  {
    id: "16526",
    english: "sky",
    transcription: "[skaɪ]",
    russian: "небо",
    tags: "nature",
    tags_json: '[""]',
  },
  {
    id: "16529",
    english: "story",
    transcription: "[ˈstôrē]",
    russian: "история",
    tags: "basic",
    tags_json: '[""]',
  },

  // дубль всех слов
  // {
  //   id: "16500",
  //   english: "ginger",
  //   transcription: "[ˈʤɪnʤə]",
  //   russian: "имбирь",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16502",
  //   english: "waterfall",
  //   transcription: "[ˈwɔ:təfɔ:l]",
  //   russian: "водопад",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16504",
  //   english: "story",
  //   transcription: "[ˈstôrē]",
  //   russian: "история",
  //   tags: "",
  //   tags_json: '[""]',
  // },

  // {
  //   id: "16506",
  //   english: "first",
  //   transcription: "[fərst]",
  //   russian: "первый",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16507",
  //   english: "sucсess",
  //   transcription: "[sucsess]",
  //   russian: "успех",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16508",
  //   english: "sunset",
  //   transcription: "[ˈsʌnset]",
  //   russian: "закат",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16509",
  //   english: "wind",
  //   transcription: "[wind]",
  //   russian: "ветер",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16510",
  //   english: "field",
  //   transcription: "[fi:ld]",
  //   russian: "поле",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16511",
  //   english: "cat",
  //   transcription: "[cat]",
  //   russian: "кот",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16520",
  //   english: "ground",
  //   transcription: "[gra:und]",
  //   russian: "земля",
  //   tags: "",
  //   tags_json: "[]",
  // },
  // {
  //   id: "16524",
  //   english: "book",
  //   transcription: "[buk]",
  //   russian: "книжка",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16525",
  //   english: "thunderstorm",
  //   transcription: " [ˈθʌndəstɔ:m]",
  //   russian: "гроза",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16526",
  //   english: "sky",
  //   transcription: "[skaɪ]",
  //   russian: "небо",
  //   tags: "",
  //   tags_json: '[""]',
  // },
  // {
  //   id: "16529",
  //   english: "story",
  //   transcription: "[ˈstôrē]",
  //   russian: "история",
  //   tags: "",
  //   tags_json: '[""]',
  // },
];
